version: '3'
services:
  exporter:
    image: golang:1.8
    volumes:
      - ./exporter/src:/go/src/exporter
    working_dir: /go/src/exporter
    ports:
      - "5000:5000"
    dns: 8.8.8.8
    command: go run main.go -u $GROWATT_USER -p $GROWATT_PASS https://server.growatt.com/
    environment:
      - GROWATT_USER=${GROWATT_USER}
      - GROWATT_PASS=${GROWATT_PASS}
    restart: always
  prometheus:
    build: ./prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - /prometheus
    ports:
      - "9090:9090"
    links:
      - exporter
    restart: always
  grafana:
    image: grafana/grafana:6.0.2
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 5ecret
    volumes:
      - /var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: always
