global:
  scrape_interval: "30s"
  scrape_timeout: "9s"
  evaluation_interval: "60s"

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#      - alertmanager:9093
#    scheme: http
#    timeout: 10s

rule_files:
  - '/etc/prometheus/prometheus.rules'
  - '/etc/prometheus/alerting.rules'

scrape_configs:
  - job_name: growatt_vn
    scrape_interval: "60s"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "exporter:5000"
